import { Alert, Linking, Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";
import { ChevronLeft, ChevronRight, FileText, KeyRound, ShieldCheck, Smartphone } from "lucide-react-native";
import { router } from "expo-router";

export default function PrivacySecurity() {
  const openPermissions = async () => { const supported = await Linking.canOpenURL("app-settings:"); if (supported) await Linking.openSettings(); else Alert.alert("Device settings", "Open your device settings to manage app permissions."); };
  return <SafeAreaView style={s.safe} edges={["top"]}><ScrollView contentContainerStyle={s.page}>
    <Pressable accessibilityLabel="Go back" onPress={() => router.back()} style={s.back}><ChevronLeft size={23} color="#211B59" /></Pressable><Text style={s.title}>Privacy & security</Text><Text style={s.sub}>Manage how 9tel protects your account and data.</Text>
    <View style={s.hero}><ShieldCheck size={28} color="#5147AF" /><View style={{flex:1}}><Text style={s.heroTitle}>Your account is protected</Text><Text style={s.heroCopy}>We use secure sign-in and protected payment pages to help keep your information safe.</Text></View></View>
    <Text style={s.heading}>PRIVACY</Text><View style={s.group}><Row icon={Smartphone} label="Device permissions" detail="Manage microphone and notification access" onPress={openPermissions}/><Row icon={FileText} label="Privacy notice" detail="See how we collect and use data" onPress={() => router.push("/(tabs)/(sub-tabs)/privacy-policy")}/></View>
    <Text style={s.heading}>SECURITY</Text><View style={s.group}><Row icon={KeyRound} label="Account security" detail="Update your name or password" onPress={() => router.push("/(tabs)/(sub-tabs)/editProfile")}/></View>
    <Text style={s.footnote}>For your protection, payment details are entered only on our secure payment providers' checkout pages.</Text>
  </ScrollView></SafeAreaView>;
}
function Row({icon:Icon,label,detail,onPress}:{icon:any;label:string;detail:string;onPress:()=>void}) { return <Pressable style={s.row} onPress={onPress}><View style={s.icon}><Icon size={19} color="#5147AF" /></View><View style={{flex:1}}><Text style={s.label}>{label}</Text><Text style={s.detail}>{detail}</Text></View><ChevronRight size={19} color="#A09BAE" /></Pressable>; }
const s=StyleSheet.create({safe:{flex:1,backgroundColor:"#F8F8FD"},page:{padding:20,paddingBottom:48},back:{width:44,height:44,borderRadius:14,backgroundColor:"#FFF",alignItems:"center",justifyContent:"center"},title:{marginTop:20,color:"#211B59",fontFamily:"Poppins-SemiBold",fontSize:26},sub:{color:"#85829B",fontFamily:"Poppins-Regular",fontSize:12,marginTop:2},hero:{marginTop:24,flexDirection:"row",gap:14,backgroundColor:"#EDEBFF",padding:18,borderRadius:22},heroTitle:{color:"#30245E",fontFamily:"Poppins-SemiBold",fontSize:14},heroCopy:{color:"#625D7A",fontFamily:"Poppins-Regular",fontSize:11,lineHeight:17,marginTop:3},heading:{color:"#211B59",fontFamily:"Poppins-SemiBold",fontSize:12,marginTop:28,marginBottom:10},group:{backgroundColor:"#FFF",borderRadius:20,paddingHorizontal:14},row:{flexDirection:"row",alignItems:"center",paddingVertical:14,borderBottomWidth:1,borderColor:"#F1F0F6"},icon:{width:40,height:40,borderRadius:14,alignItems:"center",justifyContent:"center",backgroundColor:"#EAF2FF",marginRight:12},label:{color:"#383452",fontFamily:"Poppins-Medium",fontSize:12.5},detail:{color:"#9693A7",fontFamily:"Poppins-Regular",fontSize:9.5,marginTop:1},footnote:{color:"#85829B",fontFamily:"Poppins-Regular",fontSize:10.5,lineHeight:17,textAlign:"center",marginTop:22,paddingHorizontal:12}});
