import { useTranslation } from "react-i18next";
import images from "./images";
import plantImages from "./plantImages";

// U.S. grocery-garden reference cycles. The game compresses real days into
// a playable care session while preserving real-life stage names and durations.
export const usePlantGrowth = () => {
  const { t } = useTranslation();

  const coreSeeds: any[] = [
    {
      id: 1,
      diplayName: t("plants.apple"),
      name: "Apple",
      icon: images.apple,
      iconLg: images.appleLg,
      plantImages: [
        plantImages.apple1,
        plantImages.apple2,
        plantImages.apple3,
        plantImages.apple4,
      ],
      plantSickImages: [
        plantImages.appleSick1,
        plantImages.appleSick2,
        plantImages.appleSick3,
        plantImages.appleSick4,
      ],
      plantRainImages: [
        plantImages.appleRain1,
        plantImages.appleRain2,
        plantImages.appleRain3,
        plantImages.appleRain4,
      ],
      levels: 2,
      progress: 0.2,
      emoji: "🍎",
      cycleDays: 1825,
      gardenType: "Backyard orchard",
      spacing: "Dwarf trees: 8–10 ft apart",
      stages: [
        { name: "Dormant bare-root tree", days: 30 },
        { name: "Leaf and branch establishment", days: 365 },
        { name: "Blossom and pollination seasons", days: 730 },
        { name: "First reliable fruiting window", days: 700 },
      ],
      nutrition: { strength: "Fiber + polyphenols", impact: "Supports heart-friendly snacking and digestive health." },
    },
    {
      id: 2,
      diplayName: t("plants.maize"),
      name: "Maize",
      icon: images.maize,
      iconLg: images.maizeLg,
      plantImages: [
        plantImages.maize1,
        plantImages.maize2,
        plantImages.maize3,
        plantImages.maize4,
      ],
      plantSickImages: [
        plantImages.maizeSick1,
        plantImages.maizeSick2,
        plantImages.maizeSick3,
        plantImages.maizeSick4,
      ],
      plantRainImages: [
        plantImages.maizeRain1,
        plantImages.maizeRain2,
        plantImages.maizeRain3,
        plantImages.maizeRain4,
      ],
      levels: 4,
      progress: 0.65,
      emoji: "🌽",
      cycleDays: 84,
      gardenType: "Warm-season grocery bed",
      spacing: "Rows 30–36 in apart; plants 8–12 in apart",
      stages: [
        { name: "Direct sow after frost", days: 10 },
        { name: "Vegetative leaf growth", days: 35 },
        { name: "Tassel and silk pollination", days: 20 },
        { name: "Milk stage harvest", days: 19 },
      ],
      nutrition: { strength: "Carbohydrates + fiber", impact: "Provides garden-fresh energy and supports meal satiety." },
    },
    {
      id: 3,
      name: "Mango",
      diplayName: t("plants.mango"),
      icon: images.mango,
      iconLg: images.mangoLg,
      plantImages: [
        plantImages.mango1,
        plantImages.mango2,
        plantImages.mango3,
        plantImages.mango4,
      ],
      plantSickImages: [
        plantImages.mangoSick1,
        plantImages.mangoSick2,
        plantImages.mangoSick3,
        plantImages.mangoSick4,
      ],
      plantRainImages: [
        plantImages.mangoRain1,
        plantImages.mangoRain2,
        plantImages.mangoRain3,
        plantImages.mangoRain4,
      ],
      levels: 3,
      progress: 0.5,
      emoji: "🥭",
      cycleDays: 1460,
      gardenType: "Frost-free patio/orchard fruit",
      spacing: "Container or 12–15 ft in warm zones",
      stages: [
        { name: "Transplant and root establishment", days: 90 },
        { name: "Canopy building", days: 545 },
        { name: "Flowering and fruit set", days: 365 },
        { name: "Mature fruit harvest", days: 460 },
      ],
      nutrition: { strength: "Vitamin C + carotenoids", impact: "Contributes antioxidant support and immune-friendly fruit servings." },
    },
    {
      id: 4,
      name: "Orange",
      diplayName: t("plants.orange"),
      icon: images.orange,
      iconLg: images.orangeLg,
      plantImages: [
        plantImages.orange1,
        plantImages.orange2,
        plantImages.orange3,
        plantImages.orange4,
      ],
      plantSickImages: [
        plantImages.orangeSick1,
        plantImages.orangeSick2,
        plantImages.orangeSick3,
        plantImages.orangeSick4,
      ],
      plantRainImages: [
        plantImages.orangeRain1,
        plantImages.orangeRain2,
        plantImages.orangeRain3,
        plantImages.orangeRain4,
      ],
      levels: 1,
      progress: 0.1,
      emoji: "🍊",
      cycleDays: 1095,
      gardenType: "Citrus patio/orchard fruit",
      spacing: "Container or 10–15 ft in warm zones",
      stages: [
        { name: "Young tree establishment", days: 120 },
        { name: "Flush growth and pruning", days: 365 },
        { name: "Bloom and fruit set", days: 245 },
        { name: "Color break and harvest", days: 365 },
      ],
      nutrition: { strength: "Vitamin C + hydration", impact: "Supports immune health and refreshing household fruit intake." },
    },
    {
      id: 5,
      name: "Paw Paw",
      diplayName: t("plants.pawpaw"),
      icon: images.pawpaw,
      iconLg: images.pawpawLg,
      plantImages: [
        plantImages.pawpaw1,
        plantImages.pawpaw2,
        plantImages.pawpaw3,
        plantImages.pawpaw4,
      ],
      plantSickImages: [
        plantImages.pawpawSick1,
        plantImages.pawpawSick2,
        plantImages.pawpawSick3,
        plantImages.pawpawSick4,
      ],
      plantRainImages: [
        plantImages.pawpawRain1,
        plantImages.pawpawRain2,
        plantImages.pawpawRain3,
        plantImages.pawpawRain4,
      ],
      levels: 4,
      progress: 0.9,
      emoji: "🧡",
      cycleDays: 330,
      gardenType: "Warm-zone fruiting perennial",
      spacing: "7–10 ft apart or large container",
      stages: [
        { name: "Transplant and rooting", days: 30 },
        { name: "Leaf canopy growth", days: 120 },
        { name: "Flowering and fruit set", days: 90 },
        { name: "Ripening harvest window", days: 90 },
      ],
      nutrition: { strength: "Vitamin C + beta-carotene", impact: "Adds antioxidant fruit value and colorful micronutrients." },
    },

    {
      id: 6,
      name: "Tomato",
      diplayName: "Tomato",
      icon: null,
      iconLg: null,
      plantImages: [],
      plantSickImages: [],
      plantRainImages: [],
      levels: 1,
      progress: 0.25,
      emoji: "🍅",
      cycleDays: 75,
      gardenType: "Summer raised-bed crop",
      spacing: "18–24 in apart with cage or trellis",
      stages: [
        { name: "Indoor seedling or transplant", days: 21 },
        { name: "Leaf and root establishment", days: 21 },
        { name: "Flowering and fruit set", days: 18 },
        { name: "Ripening harvest window", days: 15 },
      ],
      nutrition: { strength: "Vitamin C + potassium", impact: "Supports fresh salsa meals, hydration, and heart-friendly potassium intake." },
    },
    {
      id: 7,
      name: "Lettuce",
      diplayName: "Lettuce",
      icon: null,
      iconLg: null,
      plantImages: [],
      plantSickImages: [],
      plantRainImages: [],
      levels: 1,
      progress: 0.35,
      emoji: "🥬",
      cycleDays: 45,
      gardenType: "Cool-season salad bed",
      spacing: "Leaf lettuce 4–6 in apart; heads 10–12 in apart",
      stages: [
        { name: "Direct sow or transplant", days: 7 },
        { name: "Tender leaf growth", days: 14 },
        { name: "Head/leaf fill", days: 14 },
        { name: "Cut-and-come harvest", days: 10 },
      ],
      nutrition: { strength: "Vitamin K + folate", impact: "Adds leafy greens that support balanced meals and micronutrient variety." },
    },
    {
      id: 8,
      name: "Strawberry",
      diplayName: "Strawberry",
      icon: null,
      iconLg: null,
      plantImages: [],
      plantSickImages: [],
      plantRainImages: [],
      levels: 1,
      progress: 0.45,
      emoji: "🍓",
      cycleDays: 365,
      gardenType: "Perennial berry patch",
      spacing: "12–18 in apart with straw mulch",
      stages: [
        { name: "Crown planting", days: 30 },
        { name: "Runner and leaf growth", days: 120 },
        { name: "Flower and green berry", days: 90 },
        { name: "Red berry harvest", days: 125 },
      ],
      nutrition: { strength: "Vitamin C + manganese", impact: "Adds antioxidant-rich berries for snacks, smoothies, and family desserts." },
    },
  ];

  const seedCatalog: any[] = [
    { name: "Carrot", emoji: "🥕", cycleDays: 70, gardenType: "Cool-season root bed", spacing: "2–3 in apart in loose soil", nutrition: { strength: "Beta-carotene + fiber", impact: "Adds crunchy vitamin-rich roots for soups, salads, and snacks." } },
    { name: "Potato", emoji: "🥔", cycleDays: 100, gardenType: "Raised ridge or grow-bag crop", spacing: "Seed potatoes 10–12 in apart", nutrition: { strength: "Potassium + complex carbs", impact: "Supports filling home meals with versatile garden staples." } },
    { name: "Onion", emoji: "🧅", cycleDays: 110, gardenType: "Allium storage bed", spacing: "4–6 in apart in full sun", nutrition: { strength: "Prebiotic fiber", impact: "Builds flavorful bases for everyday cooking." } },
    { name: "Pepper", emoji: "🫑", cycleDays: 80, gardenType: "Warm-season container crop", spacing: "18 in apart with steady warmth", nutrition: { strength: "Vitamin C + color antioxidants", impact: "Adds crisp, colorful produce to quick meals." } },
    { name: "Cucumber", emoji: "🥒", cycleDays: 60, gardenType: "Trellised summer vine", spacing: "12 in apart on a trellis", nutrition: { strength: "Hydration + vitamin K", impact: "Adds refreshing snacks and salad crunch." } },
    { name: "Broccoli", emoji: "🥦", cycleDays: 85, gardenType: "Cool-season brassica bed", spacing: "18 in apart with compost", nutrition: { strength: "Vitamin C + sulforaphane", impact: "Supports hearty green side dishes." } },
    { name: "Eggplant", emoji: "🍆", cycleDays: 90, gardenType: "Warm patio fruiting crop", spacing: "24 in apart with support", nutrition: { strength: "Fiber + anthocyanins", impact: "Adds savory harvests for stews and grilling." } },
    { name: "Watermelon", emoji: "🍉", cycleDays: 95, gardenType: "Large sunny vine patch", spacing: "3–4 ft apart or strong trellis", nutrition: { strength: "Hydration + lycopene", impact: "Rewards patient players with refreshing family fruit." } },
    { name: "Pumpkin", emoji: "🎃", cycleDays: 110, gardenType: "Sprawling fall harvest vine", spacing: "3–5 ft apart", nutrition: { strength: "Vitamin A + fiber", impact: "Adds storage squash for soups and baking." } },
    { name: "Spinach", emoji: "🍃", cycleDays: 40, gardenType: "Fast cool-season greens", spacing: "3–5 in apart", nutrition: { strength: "Iron + folate", impact: "Adds quick leafy greens for omelets and smoothies." } },
    { name: "Kale", emoji: "🥬", cycleDays: 60, gardenType: "Hardy leafy-green bed", spacing: "12–18 in apart", nutrition: { strength: "Vitamin K + calcium", impact: "Keeps producing nutrient-dense leaves after harvests." } },
    { name: "Bean", emoji: "🫘", cycleDays: 55, gardenType: "Nitrogen-fixing row crop", spacing: "4–6 in apart", nutrition: { strength: "Plant protein + fiber", impact: "Adds protein-rich pods and improves garden soil." } },
    { name: "Pea", emoji: "🫛", cycleDays: 65, gardenType: "Cool trellised legume", spacing: "2 in apart along netting", nutrition: { strength: "Plant protein + vitamin C", impact: "Rewards steady watering with sweet pods." } },
    { name: "Radish", emoji: "🌶️", cycleDays: 28, gardenType: "Quick root challenge bed", spacing: "1–2 in apart", nutrition: { strength: "Vitamin C + crunch", impact: "Fast unlock crop for practicing timing." } },
    { name: "Beet", emoji: "🟣", cycleDays: 60, gardenType: "Root-and-greens bed", spacing: "3–4 in apart", nutrition: { strength: "Folate + betalains", impact: "Adds colorful roots and edible greens." } },
    { name: "Garlic", emoji: "🧄", cycleDays: 240, gardenType: "Overwinter allium bed", spacing: "4–6 in apart", nutrition: { strength: "Allicin compounds", impact: "Rewards long planning with kitchen flavor staples." } },
    { name: "Ginger", emoji: "🫚", cycleDays: 240, gardenType: "Warm container rhizome", spacing: "8 in apart in rich soil", nutrition: { strength: "Gingerols", impact: "Adds aromatic harvests for teas and sauces." } },
    { name: "Blueberry", emoji: "🫐", cycleDays: 730, gardenType: "Acid-loving berry shrub", spacing: "3–4 ft apart", nutrition: { strength: "Anthocyanins + fiber", impact: "Long-term berry unlock for advanced gardeners." } },
    { name: "Grape", emoji: "🍇", cycleDays: 1095, gardenType: "Permanent trellised vine", spacing: "6–8 ft apart", nutrition: { strength: "Polyphenols", impact: "Prestige fruit crop for dedicated farm progression." } },
    { name: "Pineapple", emoji: "🍍", cycleDays: 730, gardenType: "Tropical container fruit", spacing: "18–24 in apart", nutrition: { strength: "Vitamin C + bromelain", impact: "A premium tropical challenge crop." } },
    { name: "Banana", emoji: "🍌", cycleDays: 365, gardenType: "Tropical patio grove", spacing: "6–10 ft or large container", nutrition: { strength: "Potassium + energy", impact: "Advanced fruit crop with strong household value." } },
    { name: "Avocado", emoji: "🥑", cycleDays: 1825, gardenType: "Long-term patio/orchard tree", spacing: "Container or 15–20 ft in warm zones", nutrition: { strength: "Healthy fats + fiber", impact: "Prestige orchard unlock for patient players." } },
    { name: "Peach", emoji: "🍑", cycleDays: 1095, gardenType: "Backyard stone-fruit tree", spacing: "12–15 ft apart", nutrition: { strength: "Vitamin C + fiber", impact: "Sweet orchard harvest for late-game farmers." } },
    { name: "Cherry", emoji: "🍒", cycleDays: 1460, gardenType: "Temperate orchard tree", spacing: "12–18 ft apart", nutrition: { strength: "Antioxidants", impact: "High-tier fruit unlock with premium rewards." } },
    { name: "Cabbage", emoji: "🥬", cycleDays: 90, gardenType: "Cool brassica storage crop", spacing: "18–24 in apart", nutrition: { strength: "Vitamin K + fiber", impact: "Reliable heads for family meals and slaws." } },
    { name: "Okra", emoji: "🌿", cycleDays: 60, gardenType: "Hot-weather pod crop", spacing: "12–18 in apart", nutrition: { strength: "Fiber + magnesium", impact: "Steady picking crop for summer gardens." } },
    { name: "Celery", emoji: "🌱", cycleDays: 120, gardenType: "Moisture-loving stalk bed", spacing: "8–10 in apart", nutrition: { strength: "Hydration + vitamin K", impact: "Challenging water-management crop." } },
    { name: "Basil", emoji: "🌿", cycleDays: 35, gardenType: "Herb pot or kitchen bed", spacing: "8–12 in apart", nutrition: { strength: "Aromatic herbs", impact: "Fast herb harvest that boosts meal variety." } },
    { name: "Mint", emoji: "🌿", cycleDays: 45, gardenType: "Contained herb planter", spacing: "Pot separately to prevent spread", nutrition: { strength: "Aromatic menthol", impact: "Refreshing herb for drinks and sauces." } },
    { name: "Sunflower", emoji: "🌻", cycleDays: 90, gardenType: "Pollinator border", spacing: "12–24 in apart", nutrition: { strength: "Seeds + pollinator support", impact: "Fun visual crop that supports garden ecology." } },
  ].map((seed, index) => ({
    id: 9 + index,
    diplayName: seed.name,
    icon: null,
    iconLg: null,
    plantImages: [],
    plantSickImages: [],
    plantRainImages: [],
    levels: Math.min(5, Math.floor(index / 6) + 1),
    progress: Math.min(0.95, 0.15 + index * 0.025),
    stages: [
      { name: "Seed starting and bed prep", days: Math.max(3, Math.round(seed.cycleDays * 0.18)) },
      { name: "Vegetative growth and care", days: Math.max(7, Math.round(seed.cycleDays * 0.34)) },
      { name: "Flowering, bulking, or fruit set", days: Math.max(7, Math.round(seed.cycleDays * 0.25)) },
      { name: "Harvest and storage window", days: Math.max(5, Math.round(seed.cycleDays * 0.23)) },
    ],
    unlockLevel: Math.floor(index / 5) + 2,
    unlockPoints: 200 + index * 175,
    ...seed,
  }));

  return [...coreSeeds, ...seedCatalog].map((seed, index) => ({
    unlockLevel: seed.unlockLevel ?? Math.max(1, Math.floor(index / 4) + 1),
    unlockPoints: seed.unlockPoints ?? (index < 3 ? 0 : index * 150),
    rarity: seed.rarity ?? (index < 4 ? "Starter" : index < 14 ? "Skilled" : index < 26 ? "Expert" : "Master"),
    ...seed,
  }));
};

// Similarly for the growth messages
export const usePlantGrowthMessages = () => {
  const { t } = useTranslation();

  return [
    {
      stage: 0,
      message: "Plan the bed, prepare compost, and start seed/root establishment.",
      image: images.growth1,
    },
    {
      stage: 1,
      message: "Vegetative growth: keep moisture steady, weed, mulch, and feed lightly.",
      image: images.growth2,
    },
    {
      stage: 2,
      message: "Flowering/pollination: protect from stress and monitor pests.",
      image: images.growth3,
    },
    {
      stage: 3,
      message: "Ripening/harvest window: check produce often and record your results.",
      image: images.growth4,
    },
  ];
};
