import { useTranslation } from "react-i18next";
import images from "./images";
import plantImages from "./plantImages";

// U.S. grocery-garden reference cycles. The game compresses real days into
// a playable care session while preserving real-life stage names and durations.
export const usePlantGrowth = () => {
  const { t } = useTranslation();

  return [
    {
      id: 1,
      diplayName: t("plants.apple"),
      name: "Apple",
      icon: images.apple,
      iconLg: images.appleLg,
      plantImages: [
        plantImages.apple1,
        plantImages.apple2,
        plantImages.apple3,
        plantImages.apple4,
      ],
      plantSickImages: [
        plantImages.appleSick1,
        plantImages.appleSick2,
        plantImages.appleSick3,
        plantImages.appleSick4,
      ],
      plantRainImages: [
        plantImages.appleRain1,
        plantImages.appleRain2,
        plantImages.appleRain3,
        plantImages.appleRain4,
      ],
      levels: 2,
      progress: 0.2,
      emoji: "🍎",
      cycleDays: 1825,
      gardenType: "Backyard orchard",
      spacing: "Dwarf trees: 8–10 ft apart",
      stages: [
        { name: "Dormant bare-root tree", days: 30 },
        { name: "Leaf and branch establishment", days: 365 },
        { name: "Blossom and pollination seasons", days: 730 },
        { name: "First reliable fruiting window", days: 700 },
      ],
      nutrition: { strength: "Fiber + polyphenols", impact: "Supports heart-friendly snacking and digestive health." },
    },
    {
      id: 2,
      diplayName: t("plants.maize"),
      name: "Maize",
      icon: images.maize,
      iconLg: images.maizeLg,
      plantImages: [
        plantImages.maize1,
        plantImages.maize2,
        plantImages.maize3,
        plantImages.maize4,
      ],
      plantSickImages: [
        plantImages.maizeSick1,
        plantImages.maizeSick2,
        plantImages.maizeSick3,
        plantImages.maizeSick4,
      ],
      plantRainImages: [
        plantImages.maizeRain1,
        plantImages.maizeRain2,
        plantImages.maizeRain3,
        plantImages.maizeRain4,
      ],
      levels: 4,
      progress: 0.65,
      emoji: "🌽",
      cycleDays: 84,
      gardenType: "Warm-season grocery bed",
      spacing: "Rows 30–36 in apart; plants 8–12 in apart",
      stages: [
        { name: "Direct sow after frost", days: 10 },
        { name: "Vegetative leaf growth", days: 35 },
        { name: "Tassel and silk pollination", days: 20 },
        { name: "Milk stage harvest", days: 19 },
      ],
      nutrition: { strength: "Carbohydrates + fiber", impact: "Provides garden-fresh energy and supports meal satiety." },
    },
    {
      id: 3,
      name: "Mango",
      diplayName: t("plants.mango"),
      icon: images.mango,
      iconLg: images.mangoLg,
      plantImages: [
        plantImages.mango1,
        plantImages.mango2,
        plantImages.mango3,
        plantImages.mango4,
      ],
      plantSickImages: [
        plantImages.mangoSick1,
        plantImages.mangoSick2,
        plantImages.mangoSick3,
        plantImages.mangoSick4,
      ],
      plantRainImages: [
        plantImages.mangoRain1,
        plantImages.mangoRain2,
        plantImages.mangoRain3,
        plantImages.mangoRain4,
      ],
      levels: 3,
      progress: 0.5,
      emoji: "🥭",
      cycleDays: 1460,
      gardenType: "Frost-free patio/orchard fruit",
      spacing: "Container or 12–15 ft in warm zones",
      stages: [
        { name: "Transplant and root establishment", days: 90 },
        { name: "Canopy building", days: 545 },
        { name: "Flowering and fruit set", days: 365 },
        { name: "Mature fruit harvest", days: 460 },
      ],
      nutrition: { strength: "Vitamin C + carotenoids", impact: "Contributes antioxidant support and immune-friendly fruit servings." },
    },
    {
      id: 4,
      name: "Orange",
      diplayName: t("plants.orange"),
      icon: images.orange,
      iconLg: images.orangeLg,
      plantImages: [
        plantImages.orange1,
        plantImages.orange2,
        plantImages.orange3,
        plantImages.orange4,
      ],
      plantSickImages: [
        plantImages.orangeSick1,
        plantImages.orangeSick2,
        plantImages.orangeSick3,
        plantImages.orangeSick4,
      ],
      plantRainImages: [
        plantImages.orangeRain1,
        plantImages.orangeRain2,
        plantImages.orangeRain3,
        plantImages.orangeRain4,
      ],
      levels: 1,
      progress: 0.1,
      emoji: "🍊",
      cycleDays: 1095,
      gardenType: "Citrus patio/orchard fruit",
      spacing: "Container or 10–15 ft in warm zones",
      stages: [
        { name: "Young tree establishment", days: 120 },
        { name: "Flush growth and pruning", days: 365 },
        { name: "Bloom and fruit set", days: 245 },
        { name: "Color break and harvest", days: 365 },
      ],
      nutrition: { strength: "Vitamin C + hydration", impact: "Supports immune health and refreshing household fruit intake." },
    },
    {
      id: 5,
      name: "Paw Paw",
      diplayName: t("plants.pawpaw"),
      icon: images.pawpaw,
      iconLg: images.pawpawLg,
      plantImages: [
        plantImages.pawpaw1,
        plantImages.pawpaw2,
        plantImages.pawpaw3,
        plantImages.pawpaw4,
      ],
      plantSickImages: [
        plantImages.pawpawSick1,
        plantImages.pawpawSick2,
        plantImages.pawpawSick3,
        plantImages.pawpawSick4,
      ],
      plantRainImages: [
        plantImages.pawpawRain1,
        plantImages.pawpawRain2,
        plantImages.pawpawRain3,
        plantImages.pawpawRain4,
      ],
      levels: 4,
      progress: 0.9,
      emoji: "🧡",
      cycleDays: 330,
      gardenType: "Warm-zone fruiting perennial",
      spacing: "7–10 ft apart or large container",
      stages: [
        { name: "Transplant and rooting", days: 30 },
        { name: "Leaf canopy growth", days: 120 },
        { name: "Flowering and fruit set", days: 90 },
        { name: "Ripening harvest window", days: 90 },
      ],
      nutrition: { strength: "Vitamin C + beta-carotene", impact: "Adds antioxidant fruit value and colorful micronutrients." },
    },

    {
      id: 6,
      name: "Tomato",
      diplayName: "Tomato",
      icon: null,
      iconLg: null,
      plantImages: [],
      plantSickImages: [],
      plantRainImages: [],
      levels: 1,
      progress: 0.25,
      emoji: "🍅",
      cycleDays: 75,
      gardenType: "Summer raised-bed crop",
      spacing: "18–24 in apart with cage or trellis",
      stages: [
        { name: "Indoor seedling or transplant", days: 21 },
        { name: "Leaf and root establishment", days: 21 },
        { name: "Flowering and fruit set", days: 18 },
        { name: "Ripening harvest window", days: 15 },
      ],
      nutrition: { strength: "Vitamin C + potassium", impact: "Supports fresh salsa meals, hydration, and heart-friendly potassium intake." },
    },
    {
      id: 7,
      name: "Lettuce",
      diplayName: "Lettuce",
      icon: null,
      iconLg: null,
      plantImages: [],
      plantSickImages: [],
      plantRainImages: [],
      levels: 1,
      progress: 0.35,
      emoji: "🥬",
      cycleDays: 45,
      gardenType: "Cool-season salad bed",
      spacing: "Leaf lettuce 4–6 in apart; heads 10–12 in apart",
      stages: [
        { name: "Direct sow or transplant", days: 7 },
        { name: "Tender leaf growth", days: 14 },
        { name: "Head/leaf fill", days: 14 },
        { name: "Cut-and-come harvest", days: 10 },
      ],
      nutrition: { strength: "Vitamin K + folate", impact: "Adds leafy greens that support balanced meals and micronutrient variety." },
    },
    {
      id: 8,
      name: "Strawberry",
      diplayName: "Strawberry",
      icon: null,
      iconLg: null,
      plantImages: [],
      plantSickImages: [],
      plantRainImages: [],
      levels: 1,
      progress: 0.45,
      emoji: "🍓",
      cycleDays: 365,
      gardenType: "Perennial berry patch",
      spacing: "12–18 in apart with straw mulch",
      stages: [
        { name: "Crown planting", days: 30 },
        { name: "Runner and leaf growth", days: 120 },
        { name: "Flower and green berry", days: 90 },
        { name: "Red berry harvest", days: 125 },
      ],
      nutrition: { strength: "Vitamin C + manganese", impact: "Adds antioxidant-rich berries for snacks, smoothies, and family desserts." },
    },
  ];
};

// Similarly for the growth messages
export const usePlantGrowthMessages = () => {
  const { t } = useTranslation();

  return [
    {
      stage: 0,
      message: "Plan the bed, prepare compost, and start seed/root establishment.",
      image: images.growth1,
    },
    {
      stage: 1,
      message: "Vegetative growth: keep moisture steady, weed, mulch, and feed lightly.",
      image: images.growth2,
    },
    {
      stage: 2,
      message: "Flowering/pollination: protect from stress and monitor pests.",
      image: images.growth3,
    },
    {
      stage: 3,
      message: "Ripening/harvest window: check produce often and record your results.",
      image: images.growth4,
    },
  ];
};
